name: Docker Image CI

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world! >> file.txt
      - name: Logs
        run: |
          echo "Using usename:${{ secrets.HOST_USERNAME }}"
          echo "Using KEY:${{ secrets.KEY }}"
          echo "Using port:${{ secrets.PORT }}"
          echo "Using HOST:${{ secrets.HOST }}"
      - name: Copy file to host
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: file.txt
          target: ~/repos/images
